# render.yaml is a YAML file that describes the Render deployment.
# See https://render.com/docs/blueprint-spec for more info.
# I couldn't find a schema online, and the docs are a bit lacking, but there are
# examples on github: https://github.com/search?q=language%3Ayaml+render.yaml+%22runtime%3A+node%22&type=code
# and their api reference: https://api-docs.render.com/reference/create-service
services:
  # packages/app
  - type: web
    name: app
    runtime: node
    plan: free
    region: frankfurt
    buildCommand:
      YARN_NM_MODE=hardlinks-local yarn install && yarn workspace @theatre/app
      run cli prod build
    # todo
    startCommand: yarn workspace @theatre/app run start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app-postgres
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: GITHUB_ID
        sync: false
      - key: GITHUB_SECRET
        sync: false

      # port is provided by render
      # - key: PORT
      #   sync: false
      - key: HOST
        value: localhost
      - key: STUDIO_AUTH_JWT_PRIVATE_KEY
        sync: false
      - key: STUDIO_AUTH_JWT_PUBLIC_KEY
        sync: false
      - key: NEXT_PUBLIC_WEBAPP_URL
        fromService:
          name: app
          type: web
          envVarKey: RENDER_EXTERNAL_URL
  # packages/syncServer
  - type: web
    name: syncServer
    runtime: node
    plan: free
    region: frankfurt
    buildCommand:
      YARN_NM_MODE=hardlinks-local yarn install && yarn workspace
      @theatre/sync-server run cli prod build
    startCommand: yarn workspace @theatre/sync-server run cli prod start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: syncServer-postgres
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: HOST
        value: localhost
      # port is provided by render
      - key: APP_URL
        fromService:
          name: app
          type: web
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: app-postgres
    plan: free
    region: frankfurt
    ipAllowList: [] # only allow internal connections
    postgresMajorVersion: 15
  - name: syncServer-postgres
    plan: free
    region: frankfurt
    ipAllowList: [] # only allow internal connections
    postgresMajorVersion: 15
