version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '${DEV_DB_PORT}:5432'
    restart: always
    volumes:
      - ./.temp/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
